spring:
  application:
    name: travelo

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  config:
    import: optional:file:.env[.properties]

server:
  servlet:
    context-path: /api